### ISSUE TITLE
fix: work_contract completions

### ISSUE THREAD

**Issue by philihp** [philihp/kennerspiel#441]
The following game crashed after WITH_LAYPERSON

also the completions after a WORK_CONTRACT are all over the place.

```
CONFIG 4 france long
BUILD G01 3 1
COMMIT
CONVERT Gn
BUILD F03 3 0
USE F03 Pn
COMMIT
CUT_PEAT 0 0
COMMIT
FELL_TREES 2 0
COMMIT
USE G01
USE F03 Pn
COMMIT
USE LW1
COMMIT
BUILD G07 0 0
USE G07 PtPtPt
BUY_DISTRICT 2 HILLS
COMMIT
USE LB1 Jo
COMMIT
USE LR3
COMMIT
USE LW2 Sh
COMMIT
FELL_TREES 1 0
COMMIT
USE LB2 Gn
COMMIT
BUILD F09 3 0
USE F09
USE LR1
COMMIT
CUT_PEAT 0 0
COMMIT
BUILD G12 1 0
COMMIT
WORK_CONTRACT LG3 Pn
USE LG3 Jo
BUY_PLOT 0 MOUNTAIN
COMMIT
CUT_PEAT 0 1
COMMIT
USE LW3
COMMIT
BUILD G02 4 2
COMMIT
BUILD F04 5 0
USE F04 GnGnGnGnGn
COMMIT
USE G01
USE G07 PtPtPt
COMMIT
BUILD G13 0 0
USE G13 PnPn
COMMIT
USE LG2 Sh
COMMIT
BUILD F05 3 1
USE F05 FlFlFlFlPtBrBr
BUY_DISTRICT 2 PLAINS
COMMIT
WORK_CONTRACT F04 Pn
USE F04 GnGnGnGnGnGnGn
COMMIT
FELL_TREES 2 0
COMMIT
USE LG1
COMMIT
BUY_PLOT 2 COAST
USE LB3
COMMIT
BUILD G06 0 1
USE G06 CoCoCo
COMMIT
WORK_CONTRACT G07 Pn
```

**Comment by philihp** [comment]
This crashed the server. Maybe I shouldn't throw errors?

```
2023-07-26T19:40:23.112Z Washington_DC[7e89ebdd] file:///app/server/dist/index.mjs:36922
2023-07-26T19:40:23.112Z Washington_DC[7e89ebdd] throw new Error(`Unable to parse [${command2.join(",")}]`);
2023-07-26T19:40:23.112Z Washington_DC[7e89ebdd] ^
2023-07-26T19:40:23.112Z Washington_DC[7e89ebdd] 
2023-07-26T19:40:23.112Z Washington_DC[7e89ebdd] Error: Unable to parse [,WITH_LAYBROTHER]
2023-07-26T19:40:23.112Z Washington_DC[7e89ebdd] at file:///app/server/dist/index.mjs:36922:15
2023-07-26T19:40:23.112Z Washington_DC[7e89ebdd] at e2.run (file:///app/server/dist/index.mjs:19665:16)
2023-07-26T19:40:23.112Z Washington_DC[7e89ebdd] at e2.otherwise (file:///app/server/dist/index.mjs:19645:29)
2023-07-26T19:40:23.112Z Washington_DC[7e89ebdd] at reducer2 (file:///app/server/dist/index.mjs:36921:11)
2023-07-26T19:40:23.112Z Washington_DC[7e89ebdd] at Impl.move (file:///app/server/dist/index.mjs:37181:69)
2023-07-26T19:40:23.112Z Washington_DC[7e89ebdd] at ImplWrapper._getResult (file:///app/server/dist/index.mjs:38508:21)
2023-07-26T19:40:23.112Z Washington_DC[7e89ebdd] at async ImplWrapper.getResult (file:///app/server/dist/index.mjs:38485:17)
2023-07-26T19:40:23.112Z Washington_DC[7e89ebdd] at async Object.onMessage (file:///app/server/dist/index.mjs:38761:22)
2023-07-26T19:40:23.113Z Washington_DC[7e89ebdd] 
2023-07-26T19:40:23.113Z Washington_DC[7e89ebdd] Node.js v18.17.0
```
